scala_library(
    dependencies=[
        '3rdparty/jvm/com/twitter:finagle-http',
        '3rdparty/jvm/com/twitter:finatra-http',
        '3rdparty/jvm/com/twitter:finatra-jackson',
        '3rdparty/jvm/org/sangria-graphql',
    ],
)